config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'static#home'
  get '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  get '/strains/most_reviewed', to: 'strains#most_reviewed'

  get '/strains/alphabetized_by_name', to: 'strains#alpha'
  
  resources :strains do 
    resources :reviews
  end
  
  resources :categories, only: [:index, :show]

  resources :users, except: [:new, :create, :index] do
    resources :favorites, only: [:index, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews, :dependent => :destroy
    has_many :strains, through: :reviews
    has_many :favorite_strains
    has_many :favorites, through: :favorite_strains, source: :strain, :dependent => :destroy
    has_one_attached :profile_picture
    has_secure_password

    validates :username, :email, presence: true, uniqueness: true
    validates :profile_picture, content_type: {in: %w[image/jpeg image/gif image/png image/pdf],
                                            message: "must be a valid image format"}


    def display_profile_picture
        if profile_picture
            profile_picture.variant(resize_to_limit: [300, 300])
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:show, :edit]

    def new
       redirect_if_logged_in
        @user = User.new
    end

    def create
        @user = User.new(user_params(:username, :profile_picture, :email, :birthday, :password, :password_confirmation))
        @user.profile_picture.attach(params[:profile_picture])
        if @user.save
            log_in @user
            redirect_to @user, notice: "You have successfully created an account!"
        else
            render :new
        end
    end

    def show
        @strains = current_user.strains.uniq
        @reviews = current_user.reviews
        @favorites = current_user.favorites
    end

    def edit
       @user = current_user
    end

    def update
        @user = current_user   
        if @user.update(user_params(:username, :profile_picture, :password, :password_confirmation))
            redirect_to user_path(@user)
        else 
            render :edit
        end
    end

    def destroy
        @user = current_user
        @user.delete
        session.clear
        redirect_to login_path
    end

    private

    def user_params(*args)
        params.require(:user).permit(*args)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_with(model: @user, url: user_path(@user)) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
        </br>
        </br>
        <%= f.label :profile_picture %>
        <%= f.file_field :profile_picture,  accept: "image/jpeg, image/gif, image/png, image/pdf"%>
        </br>
    <%= f.label :password %>
    <%= f.password_field :password %>
        </br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>


    <%= f.submit  %>
<% end %>

app/views/users/_signup_form.html.erb
<%= form_with(model: @user, url: signup_path)  do |f| %>
  
    <div class="mb-3">
      <div class="form-label">
        <%= f.label :email %>
      </div>
      <%= f.email_field :email %>
      <div id="emailHelp" class="form-text">We will never share your email with anyone else.</div>
    </div>
    
    <div class="mb-3">
      <div class="form-label">
        <%= f.label :username %>
      </div>
      <div class="form-text">
        <%= f.text_field :username %>
      </div>
      </div>
      
      <div class="mb-3">
        <div class="form-label">
          <%= f.label :password %>
        </div>
        <div class="form-text">
          <%= f.password_field :password %>
        </div>
          </br>
  
  
      <div class="mb-3">
        <div class="form-label">
          <%= f.label :password_confirmation %>
        </div>
        <div class="form-text">
          <%= f.password_field :password_confirmation %>
        </div>
          </br>
  
      </div>
      <div class="btn btn-primary"><%= submit_tag "Signup" %></div>
      
  <% end %>

app/views/users/edit.html.erb
<h1 class="text-center"> EDIT PROFILE </h1>
<%= render partial: 'layouts/error', locals: {object: @user} %>
<%= render partial: 'edit_form' %>

app/views/users/new.html.erb
<h1 class="text-center">Signup</h1>

<%= render partial: 'layouts/error', locals: {object: @user} %>

<div class="card text-center" style="width: 36rem;">
  <div class="card-body">
    <%= render partial: 'signup_form' %>
  </div>
</div>

<%= button_to "Log in with Google", '/auth/google_oauth2'  %>

app/views/users/show.html.erb
     <%= image_tag current_user.display_profile_picture if current_user.profile_picture.attached? %>


<h1>WELCOME <%= current_user.username %></h1>

<%= current_user.email %></br>

<%= button_to "Logout", logout_path %>
<%= button_to "Delete Account", user_path(current_user), method: :delete %> 
<%= link_to "Edit Account", edit_user_path(current_user)%> 

<h3><%= link_to "Your Favorites", user_favorites_path(current_user) %></h3>
</br>
<h3>Your reviews</h3>
<%= render(partial: 'reviews/review', collection: @reviews) || "No reviews found"%>

 