config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'static#home'
  get '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  get '/strains/most_reviewed', to: 'strains#most_reviewed'

  get '/strains/alphabetized_by_name', to: 'strains#alpha'
  
  resources :strains do 
    resources :reviews
  end
  
  resources :categories, only: [:index, :show]

  resources :users, except: [:new, :create, :index] do
    resources :favorites, only: [:index, :create]
  end
end

app/models/strain.rb
class Strain < ApplicationRecord
  belongs_to :category
  has_many :reviews
  has_many :users, through: :reviews
  has_many :favorite_strains
  has_many :favorited_by, through: :favorite_strains, source: :user

  validates :name, presence: true, uniqueness: true
  
  scope :most_reviews, ->{ order(reviews_count: :desc) }
  scope :by_thc_content, ->{ order(thc_content: :desc) }
  scope :alphabetized_by_name, ->{ order(name: :desc) }

  def self.search_by_name(search)
    if search
      where("name LIKE ?", "%#{search}%")
    else
      all
    end
  end

  def average_rating
    if reviews.empty?
      n = "No reviews"
    else
      n = reviews.collect do |review|
        review.rating
    end
    n.sum / n.length
  end
  end

  def category_name
    self.category.name
  end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
    before_action :find_strain, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_logged_in, except: [:show, :index, :most_reviewed]


    def new
        @strain = Strain.new
    end

    def create
        @strain = Strain.new(strain_params)
        if @strain.save
            redirect_to strain_path(@strain), notice: "You have sucessfully created a strain!"
        else
            render :new
        end
    end

    def index
        if params[:search]
            @strains = Strain.search_by_name(params[:search])
                if @strains.empty?
                    flash.now[:alert] = "NO STRAINS FOUND"
                end
        else
            @strains = Strain.all
        end
    end

    def show
        @user = current_user
    end

    def edit
    end

    def update
        if @strain.update(strain_params)
            redirect_to strain_path(@strain)
        else 
            render :edit
        end
    end

    def destroy
        @strain.destroy
        redirect_to strains_path
    end

    def most_reviewed
        @strain = Strain.most_reviews.first
    end
    
    def alpha
        @strains = Strain.alphabetized_by_name
    end

    private

    def strain_params
        params.require(:strain).permit(:name, :description, :thc_content, :category_id)
    end

    def find_strain
        @strain = Strain.find_by(id: params[:id]) or not_found
    end
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/views/strains/_form.html.erb
<%= render partial: 'layouts/error', locals: {object: @strain} %>

<div class="card text-center">
    <div class="card-body">

    <%= form_for(@strain) do |f| %>
        
        <div class="mb-3">
            <div class="form-label">
                <%= f.label :name %>
            </div>
            <div class="form-text">
                <%= f.text_field :name %>
            </div>
        </div>
        
        <div class="mb-3">
            <div class="form-label">
                <%= f.label :category %>
            </div>
            <div class="form-text">
                <%= f.collection_select :category_id, Category.all, :id, :name %>
            </div>
        </div>
  
        <div class="mb-3">
            <div class="form-label">
                <%= f.label :thc_content %>
            </div>
            <div class="form-text">
                <%= f.number_field :thc_content %>
            </div>
        </div>

        <div class="mb-3">
            <div class="form-label">
                <%= f.label :description %>
                </div>
            <div class="form-text">
                <%= f.text_area :description %>
            </div>
        </div>

        <%= f.submit %>
    <% end %>
    </div>
</div>

app/views/strains/_strain.html.erb
<div class="col">
    <div class="card">
    <div class="card-body">
      <h5 class="card-title"> <%= strain.name %></h5>
      <p class="card-text"><%= strain.category_name %></p>
      <p class="card-text">THC Content: <%= strain.thc_content %>%</p>
      <p class="card-text">Average Rating: <%= strain.average_rating %></p>
      <p class="card-text"><%= strain.description %></p>
      <a href="<%= strain_path(strain) %>" class="btn btn-primary">view strain page</a>
    </div>
  </div>
</div>

app/views/strains/alpha.html.erb
<ul>
<% @strains.each do |strain| %>
    <li><%= strain.name %></li>
<% end %>
</ul>

app/views/strains/edit.html.erb
<h1 class= "text-center">Edit <%= @strain.name %></h1>

<%= render partial: 'form' %>

app/views/strains/index.html.erb
<h1 class="text-center">All Strains</h1>
<%= link_to "New Strain", new_strain_path %>

<%= form_with(url: strains_path, method: :get) do |f| %>
    <%= f.label :search, "Search strains by name" %>
    <%= f.text_field :search %>
    <%= f.submit "Search" %>
<% end %>

</br>
 <div class="row row-cols-1 row-cols-md-2 g-4">
    <%= render @strains  %>  
</div>

app/views/strains/most_reviewed.html.erb
<%= render @strain %>
<%= @strain.reviews_count %> Reviews

<%= render partial: 'reviews/review', collection: @strain.reviews %>

app/views/strains/new.html.erb
<h1 class="text-center"> Create a new strain </h1>

<%= render partial: 'form' %>
    

    

    

app/views/strains/show.html.erb
<h1 class="text-center"><%= @strain.name %></h1></br>
<%= favorite_button %>

<%= @strain.category_name %></br>
<p>Description: <%= @strain.description.capitalize %></p>
<p>THC Content: <%= @strain.thc_content %>%</p></br>
<%= button_to "Delete Strain", strain_path(@strain), method: :delete %>
<%= link_to "Edit Strain", edit_strain_path(@strain) %></br>
<%= link_to "All Reviews", strain_reviews_path(@strain) %></br>
<%= link_to "New Review", new_strain_review_path(@strain) %></br>