config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'static#home'
  get '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  get '/strains/most_reviewed', to: 'strains#most_reviewed'

  get '/strains/alphabetized_by_name', to: 'strains#alpha'
  
  resources :strains do 
    resources :reviews
  end
  
  resources :categories, only: [:index, :show]

  resources :users, except: [:new, :create, :index] do
    resources :favorites, only: [:index, :create]
  end
end

app/views/layouts/_error.html.erb
<% if object && object.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="branding">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #198754;">
        <small>&copy; 2021 <strong>CannaStore</strong></small>
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
        </ul>
    </nav>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #198754;">
<a class="navbar-brand" href="/"> <h1> CannaStore </h1></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="<%= strains_path %>">Strains</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="<%= categories_path %>">Categories</a>
    </li>
      <% if logged_in? %>
      <li class="nav-item">
        <a class="nav-link" href=" <%= user_path(current_user) %>">Account</a>
      </li>
      <li class="nav-item">
      </li>

    <ul class="nav navbar-nav ml-auto">
      <% else %>
      <li class="nav-item">
        <a class="nav-link" href="<%= signup_path %>"><span class="fas fa-user"></span> Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= login_path %>"><span class="fas fa-sign-in-alt"></span> Login</a>
      </li>
      <% end %>
  </ul>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CannaStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  </head>

  <body>
  
    <%= render 'layouts/navbar' %>
    <% flash.each do |key, value| %>
      <%= value %>
      <% end %>
    
      <%= yield %>
     
    <%= render 'layouts/footer' %>
  </body>
</html>